### ISSUE TITLE
mongoDB 설명서

### ISSUE THREAD

**Issue by CutTheWire** [TreeNut-KR/ChatBot_Docker#11]
# Docker로 MongoDB 구축 및 사용 설명서

이 문서에서는 Docker를 사용하여 MongoDB를 구축하는 방법과 MongoDB Compass를 사용하여 MongoDB에 접속하는 방법을 설명합니다. 또한, Python을 사용하여 MongoDB에 연결하고 데이터베이스 목록을 출력하는 코드도 포함되어 있습니다.

### 1.1. Dockerfile 작성

먼저, 프로젝트 디렉토리에 `mongo` 디렉토리를 만들고 그 안에 `Dockerfile`과 `mongod.conf` 파일을 생성합니다.

### `mongo/Dockerfile`

```
# 베이스 이미지로 MongoDB를 사용합니다.
FROM mongo:latest

# 유지관리자를 설정합니다.
LABEL maintainer="sjmbee04@gmail.com"

# MongoDB 설정 파일을 컨테이너 내 적절한 위치로 복사합니다.
COPY mongod.conf /etc/mongod.conf

# MongoDB 포트를 오픈합니다.
EXPOSE 27017

# 컨테이너 시작 시 MongoDB를 실행하도록 설정합니다.
CMD ["mongod", "--config", "/etc/mongod.conf"]
```

### `mongo/mongod.conf`

```
# MongoDB 설정 파일

# 네트워크 인터페이스 설정
net:
  port: 27017
  bindIp: 0.0.0.0

# 데이터베이스 경로 설정
storage:
  dbPath: /data/db

# 시스템 로그 설정
systemLog:
  destination: file
  path: /var/log/mongodb/mongod.log
  logAppend: true

# 보안 설정
security:
  authorization: enabled

# 프로세스 관리 설정
processManagement:
  fork: false
```

### 1.2. Docker Compose 설정

프로젝트 루트 디렉토리에 `docker-compose.yml` 파일을 작성합니다.

### `docker-compose.yml`

```yaml
version: '3.8'

services:
  mongodb:
    build: ./mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ADMIN_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ADMIN_PASSWORD}
      MONGO_DATABASE: ${MONGO_DATABASE}
    volumes:
      - ./mongo/data:/data/db
      - ./mongo/log:/var/log/mongodb
```

### 1.3. 환경 변수 파일 작성

프로젝트 루트 디렉토리에 `.env` 파일을 작성합니다.

### `.env`

```
MONGO_ADMIN_USER=root
MONGO_ADMIN_PASSWORD=1234
MONGO_DATABASE=chatbot
```

### 1.4. Docker 컨테이너 실행

터미널에서 아래 명령어를 실행하여 Docker 컨테이너를 빌드하고 실행합니다.

```bash
docker-compose up --build
```

### 2.1. MongoDB Compass 다운로드 및 설치

1. [[MongoDB Compass 다운로드 페이지](https://www.mongodb.com/try/download/compass)](https://www.mongodb.com/try/download/compass)로 이동합니다.
2. Windows 버전을 선택하고 다운로드합니다.
3. 다운로드한 설치 파일을 실행하여 MongoDB Compass를 설치합니다.

### 2.2. MongoDB Compass 설정 및 연결

1. MongoDB Compass를 실행합니다.
2. **New Connection**을 클릭합니다.
3. Connection String 입력창에 아래 문자열을 입력합니다:
    
    ```
    mongodb://localhost:27017
    ```
    
4. **Connect** 버튼을 클릭합니다.
5. 인증이 필요한 경우, 아래와 같이 연결 문자열을 입력합니다:
    
    ```
    mongodb://root:1234@localhost:27017/chatbot?authSource=admin
    ```
    
6. 연결에 성공하면 MongoDB Compass에서 데이터베이스, 컬렉션 등을 확인하고 관리할 수 있습니다.

### 3.1. `pymongo` 라이브러리 설치

터미널에서 아래 명령어를 실행하여 `pymongo` 라이브러리를 설치합니다.

```bash
pip install pymongo
```

### 3.2. Python 코드 작성

아래 Python 코드를 사용하여 MongoDB에 연결하고 데이터베이스 목록을 출력합니다.

### `checking.py`

```python
from pymongo import MongoClient
from typing import List
from dotenv import load_dotenv
import os

def get_database_names(host: str, port: int, username: str, password: str, auth_source: str) -> List[str]:
    """
    MongoDB에 연결하여 데이터베이스 목록을 반환합니다.

    Parameters:
        host (str): MongoDB 호스트
        port (int): MongoDB 포트
        username (str): MongoDB 사용자 이름
        password (str): MongoDB 비밀번호
        auth_source (str): 인증 소스 데이터베이스

    Returns:
        List[str]: 데이터베이스 이름 목록
    """
    # MongoDB 클라이언트 생성
    client = MongoClient(
        host=host,
        port=port,
        username=username,
        password=password,
        authSource=auth_source
    )
    
    # 데이터베이스 목록 가져오기
    db_names = client.list_database_names()
    
    return db_names

if __name__ == "__main__":
    load_dotenv()
    # 환경 변수 또는 직접 값을 설정하여 사용
    HOST = "localhost"
    PORT = 27017
    USERNAME = os.getenv("MONGO_ADMIN_USER")
    PASSWORD = os.getenv("MONGO_ADMIN_PASSWORD")
    AUTH_SOURCE = "admin"

    # 데이터베이스 목록 출력
    databases = get_database_names(HOST, PORT, USERNAME, PASSWORD, AUTH_SOURCE)
    print("MongoDB 데이터베이스 목록:")
    for db_name in databases:
        print(f" - {db_name}")
```

이 코드를 실행하면 MongoDB 서버에 연결하여 데이터베이스 목록을 출력합니다.

### 코드 실행

`checking.py`를 실행하면 초기상태의 경우 아래와 같이 표시됩니다. 

```bash
MongoDB 데이터베이스 목록:
 - admin
 - config
 - local
```
